[phases.setup]
nixPkgs = ["nodejs_20", "python3", "gcc", "gnumake"]

[phases.install]
cmds = ["npm install", "cd client && npm install", "cd server && npm install"]

[phases.build]
cmds = ["cd client && npm run build"]

[start]
cmd = "npm start"
